# Generated by Django 5.0.2 on 2024-02-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_details',
            fields=[
                ('book_name', models.CharField(max_length=30)),
                ('author_name', models.CharField(max_length=20)),
                ('book_no', models.IntegerField(primary_key=True, serialize=False)),
                ('book_price', models.IntegerField()),
                ('published_year', models.IntegerField()),
            ],
        ),
    ]
